import React, { Component } from 'react';

class News extends Component{
    render(){
        return(
            <div className="news">
                <h2>News</h2>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus dapibus nibh vitae turpis semper, id viverra nisl euismod. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam mollis massa quis magna pulvinar, ut laoreet felis tincidunt. Quisque elit dolor, lacinia tristique fringilla in, placerat vel sapien. Ut suscipit libero justo, rutrum condimentum mauris tincidunt a. Vivamus elementum at tellus eget facilisis. Aliquam non risus vel augue elementum molestie vel vitae augue. Nullam ornare eu nibh ac faucibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque enim orci, dapibus eget auctor dictum, tincidunt et ipsum. Nunc blandit justo nec erat bibendum, posuere fermentum orci aliquet. In posuere odio nunc, id sodales quam pharetra sagittis. Praesent erat est, aliquam id varius sit amet, pharetra vitae magna. Vestibulum pellentesque vehicula libero, id ornare enim sagittis id. Praesent consequat cursus placerat.</p>
                <p>Vestibulum condimentum nunc vel sem vulputate tincidunt. Suspendisse accumsan id turpis et molestie. Duis gravida massa congue nibh imperdiet laoreet. Ut leo velit, sollicitudin sit amet leo ut, ultricies viverra mauris. Maecenas finibus augue ligula, eu feugiat erat ornare feugiat. Suspendisse imperdiet diam elit, id congue tortor lobortis mollis. Duis maximus odio sed sem condimentum, id dapibus erat posuere. Vestibulum mollis neque ligula, ac convallis lectus tristique a. Suspendisse imperdiet sollicitudin dui, nec eleifend libero laoreet a. Duis et tempor quam. Pellentesque ultricies augue ut velit scelerisque, id convallis arcu facilisis. Nullam a diam et ipsum interdum mollis. Cras sagittis orci orci, eu suscipit sem dignissim lacinia. Pellentesque ornare, neque in laoreet pharetra, erat mi eleifend nisi, vitae fringilla lorem ipsum eu sem.</p>
                <p>Duis quis nibh at ligula fringilla mattis sed sed mi. Nullam eu pellentesque mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse pellentesque, mauris in elementum varius, arcu purus convallis nisi, vitae bibendum metus ante condimentum justo. In eleifend non eros eu venenatis. Donec et massa nec quam imperdiet malesuada nec sit amet orci. Duis consequat aliquet ante, ac ornare dui. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus sagittis cursus risus id fringilla. Nam hendrerit enim nec orci imperdiet, vel placerat sem tempus.</p>
                <p>Cras euismod et nibh a lacinia. Fusce tempor lacus eu ultrices efficitur. Maecenas in porttitor ex, id congue tellus. Vivamus dignissim pellentesque turpis in consequat. Proin ac ultricies libero, et malesuada orci. Aenean at condimentum justo. Sed blandit felis ac tristique dapibus. Duis feugiat enim augue, a pellentesque libero tempus vel. Ut massa tellus, maximus eu dictum tincidunt, posuere quis augue. Sed neque nunc, gravida non sapien eget, interdum pretium purus. Quisque libero turpis, ultricies ac elit vulputate, feugiat pretium est.</p>
                <p>Nunc tempor, justo sed venenatis hendrerit, est nunc scelerisque est, in dapibus nisl justo eget dui. Aenean sodales aliquet lacus, ut suscipit nulla sollicitudin id. Nullam ac efficitur libero, ac vehicula ante. Suspendisse et velit diam. Sed eget porta nibh. Cras congue tellus in placerat lobortis. Morbi mattis gravida est, eu pellentesque mauris vehicula ac. Donec convallis semper tellus. Nunc ac interdum metus, a lobortis nisl. Nunc rutrum ligula et dignissim pretium.</p>
            </div>
        );
    }
}

export default News;